name: C/C++ CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: install_dependencies
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
            sudo apt-get update -y -qq
            sudo apt-get update && sudo apt-get install xorg-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev libsdl2-dev libsdl2-ttf-dev
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install SDL2
            brew install SDL2_image
            brew install SDL2_ttf
          fi
          if [ "$RUNNER_OS" == "Windows" ]; then
            curl -L -O https://www.libsdl.org/release/SDL2-devel-2.28.4-VC.zip
            curl -L -O https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.2/SDL2_ttf-devel-2.20.2-VC.zip
            7z x SDL2-devel-2.28.4-VC.zip -oSDL2
            7z x SDL2_ttf-devel-2.20.2-VC.zip -oSDL2_ttf
          fi

      - name: build
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            export SDL2_DIR=D:\\a\\gbemu\\gbemu\\SDL2\\SDL2-2.28.4\\cmake
            export SDL2_ttf_DIR=d:\\a\\gbemu\\gbemu\\SDL2_ttf\\SDL2_ttf-2.20.2\\cmake
          fi
          mkdir build
          cd build
          cmake ..
          cmake --build . -j 8
