name: C/C++ CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: install_dependencies
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
            sudo apt-get update -y -qq
            sudo apt-get update && sudo apt-get install xorg-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev libsdl2-dev
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install SDL2
            brew install SDL2_image
          fi
          if [ "$RUNNER_OS" == "Windows" ]; then
            curl -L -O https://www.libsdl.org/release/SDL2-devel-2.0.14-mingw.zip
            7z x SDL2-devel-2.0.14-mingw.zip -oSDL2
            ls SDL2/SDL2-2.0.14/
          fi

      - name: build
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            export SDL2_DIR=${{ github.workspace }}/SDL2/SDL2-2.0.14
          fi
          mkdir build
          cd build
          cmake ..
          cmake --build . -j 8
